// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

/*
Package door is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	Event
*/
package door

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MethodEnum int32

const (
	MethodEnum_OPEN   MethodEnum = 0
	MethodEnum_CLOSE  MethodEnum = 1
	MethodEnum_GET    MethodEnum = 2
	MethodEnum_POST   MethodEnum = 3
	MethodEnum_PUT    MethodEnum = 4
	MethodEnum_DELETE MethodEnum = 5
)

var MethodEnum_name = map[int32]string{
	0: "OPEN",
	1: "CLOSE",
	2: "GET",
	3: "POST",
	4: "PUT",
	5: "DELETE",
}
var MethodEnum_value = map[string]int32{
	"OPEN":   0,
	"CLOSE":  1,
	"GET":    2,
	"POST":   3,
	"PUT":    4,
	"DELETE": 5,
}

func (x MethodEnum) String() string {
	return proto.EnumName(MethodEnum_name, int32(x))
}
func (MethodEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Event struct {
	Path   string     `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Method MethodEnum `protobuf:"varint,2,opt,name=method,enum=door.MethodEnum" json:"method,omitempty"`
	Data   []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Event) GetMethod() MethodEnum {
	if m != nil {
		return m.Method
	}
	return MethodEnum_OPEN
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "door.Event")
	proto.RegisterEnum("door.MethodEnum", MethodEnum_name, MethodEnum_value)
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xc1, 0xab, 0x82, 0x40,
	0x10, 0x87, 0xdf, 0xea, 0xea, 0x7b, 0xce, 0x8b, 0x18, 0xe6, 0xe4, 0x51, 0x3a, 0x2d, 0x1d, 0x3c,
	0xd4, 0x9f, 0x50, 0x43, 0x04, 0x96, 0xa2, 0xdb, 0xa1, 0xa3, 0xa1, 0xe0, 0x45, 0x57, 0x64, 0xeb,
	0xef, 0x8f, 0x5d, 0x82, 0x6e, 0x3f, 0xbe, 0x6f, 0x3e, 0x18, 0xf8, 0xef, 0x5f, 0xfd, 0x64, 0xf3,
	0x79, 0x31, 0xd6, 0x90, 0xec, 0x8c, 0x59, 0x36, 0x77, 0x88, 0xd8, 0x41, 0x22, 0x90, 0x73, 0x6b,
	0x87, 0x54, 0x64, 0x42, 0x25, 0xb5, 0xdf, 0xa4, 0x20, 0x1e, 0x7b, 0x3b, 0x98, 0x2e, 0x0d, 0x32,
	0xa1, 0xd6, 0x3b, 0xcc, 0x5d, 0x93, 0x5f, 0x3c, 0xe3, 0xe9, 0x39, 0xd6, 0x1f, 0xef, 0xea, 0xae,
	0xb5, 0x6d, 0x1a, 0x66, 0x42, 0xad, 0x6a, 0xbf, 0xb7, 0x67, 0x80, 0xef, 0x25, 0xfd, 0x81, 0x2c,
	0x2b, 0xbe, 0xe2, 0x0f, 0x25, 0x10, 0x1d, 0x8a, 0xb2, 0x61, 0x14, 0xf4, 0x0b, 0xe1, 0x89, 0x35,
	0x06, 0xce, 0x56, 0x65, 0xa3, 0x31, 0x74, 0xa8, 0xba, 0x69, 0x94, 0x04, 0x10, 0x1f, 0xb9, 0x60,
	0xcd, 0x18, 0x3d, 0x62, 0xff, 0xf2, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x92, 0xc3, 0x31, 0xef,
	0xc1, 0x00, 0x00, 0x00,
}
