// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package chat is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Chat
	Chats
*/
package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Chat struct {
	Nick      string `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
	Context   string `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Chat) Reset()                    { *m = Chat{} }
func (m *Chat) String() string            { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()               {}
func (*Chat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Chat) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Chat) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *Chat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Chats struct {
	Chats []*Chat `protobuf:"bytes,1,rep,name=chats" json:"chats,omitempty"`
}

func (m *Chats) Reset()                    { *m = Chats{} }
func (m *Chats) String() string            { return proto.CompactTextString(m) }
func (*Chats) ProtoMessage()               {}
func (*Chats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Chats) GetChats() []*Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

func init() {
	proto.RegisterType((*Chat)(nil), "chat.Chat")
	proto.RegisterType((*Chats)(nil), "chat.Chats")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x82, 0xb8, 0x58, 0x9c, 0x33,
	0x12, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x32, 0x93, 0xb3, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0x8a, 0x12, 0x09, 0x26,
	0xb0, 0x30, 0x8c, 0x2b, 0x24, 0xc3, 0xc5, 0x59, 0x92, 0x99, 0x9b, 0x5a, 0x5c, 0x92, 0x98, 0x5b,
	0x20, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x10, 0x50, 0xd2, 0xe4, 0x62, 0x05, 0x99, 0x59,
	0x2c, 0xa4, 0xc0, 0xc5, 0x0a, 0xb2, 0xa4, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x4b,
	0x0f, 0x6c, 0x3d, 0x48, 0x2e, 0x08, 0x22, 0x91, 0xc4, 0x06, 0x76, 0x8b, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x1c, 0xd4, 0xcc, 0xbc, 0x99, 0x00, 0x00, 0x00,
}
